CREATE TABLE IF NOT EXISTS `Project-cveId` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `cveId` VARCHAR(30) NOT NULL,
    `Description` VARCHAR(800) NOT NULL,
    `Published Date Severity` VARCHAR(30) NOT NULL,
    `References` VARCHAR(800) NOT NULL,


    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    UNIQUE('cveId')
)